//! R sources embedded into the binary and helpers for assembling them into
//! runnable scripts.
//!
//! The R code lives in plain `.R` files under `assets/r/` so it can be read,
//! linted, and edited with ordinary R tooling. Rust owns the configuration:
//! each script is assembled by prepending a generated block of top-level R
//! assignments ([`RConfig`]) to one or more static R sources, in order. There
//! is no templating step; the static sources simply reference the variables
//! that the configuration block defines, and each `.R` file documents the
//! variables it expects in its header comment.

use std::{fmt::Write as _, path::Path};

use crate::util;

/// Embeds an R source file from `assets/r/` at compile time.
///
/// A missing or renamed file fails the build, so the embedded sources can
/// never drift out of sync with the binary.
macro_rules! r_asset {
    ($name:literal) => {
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/r/", $name))
    };
}

/// Monkey patches for the pkgdepends install scheduler and the P3M rate
/// limiter shared by pak and xfun downloads.
pub const PKGDEPENDS_PATCH: &str = r_asset!("patch-pkgdepends.R");

/// Shared prelude for the revdep install and check scripts: workspace and
/// library setup, parallelism options, and installation helpers.
pub const REVDEP_PRELUDE: &str = r_asset!("revdep-prelude.R");

/// Installs the package, its dependencies, and its reverse dependencies into
/// the revdep library.
pub const REVDEP_INSTALL: &str = r_asset!("revdep-install.R");

/// Runs `xfun::rev_check()` against the prepared revdep library.
pub const REVDEP_RUN: &str = r_asset!("revdep-run.R");

/// Resolves Ubuntu system requirements for reverse dependencies and prints
/// them as JSON.
pub const SYSREQS: &str = r_asset!("sysreqs.R");

/// Comment that opens every generated configuration block.
const CONFIG_HEADER: &str = "# Configuration generated by revdeprun ----";

/// A block of top-level R assignments generated from Rust values.
///
/// Values are rendered as R literals with proper escaping, so callers never
/// hand-build R source. Assignments are emitted in insertion order.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct RConfig {
    assignments: Vec<(String, String)>,
}

impl RConfig {
    /// Creates an empty configuration block.
    pub fn new() -> Self {
        Self::default()
    }

    /// Assigns a character scalar.
    pub fn string(self, name: &str, value: &str) -> Self {
        self.assign(name, util::r_string_literal(value))
    }

    /// Assigns a filesystem path as a character scalar.
    pub fn path(self, name: &str, value: &Path) -> Self {
        self.string(name, &value.to_string_lossy())
    }

    /// Assigns a non-negative whole number.
    ///
    /// The value is rendered as a bare decimal literal (for example `8`),
    /// which R reads as a double. The scripts only use these values as
    /// counts, where doubles and integers behave identically.
    pub fn integer(self, name: &str, value: usize) -> Self {
        self.assign(name, value.to_string())
    }

    /// Renders the block as R source, terminated by a newline.
    pub fn render(&self) -> String {
        let mut source = format!("{CONFIG_HEADER}\n");
        for (name, expression) in &self.assignments {
            // Writing to a `String` cannot fail.
            let _ = writeln!(source, "{name} <- {expression}");
        }
        source
    }

    fn assign(mut self, name: &str, expression: String) -> Self {
        assert!(
            is_r_identifier(name),
            "{name:?} is not a syntactically valid R variable name"
        );
        self.assignments.push((name.to_owned(), expression));
        self
    }
}

/// Assembles a runnable R script: the configuration block first, followed by
/// each static source in the given order, separated by blank lines.
pub fn assemble(config: &RConfig, sources: &[&str]) -> String {
    let capacity = sources.iter().map(|source| source.len() + 1).sum::<usize>();
    let mut script = String::with_capacity(capacity);
    script.push_str(&config.render());
    for source in sources {
        script.push('\n');
        script.push_str(source);
    }
    script
}

/// Returns whether `name` is a syntactically valid (ASCII) R variable name:
/// a letter, or a dot not followed by a digit, followed by letters, digits,
/// dots, or underscores.
fn is_r_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    let rest = &name[first.len_utf8()..];
    let valid_start = first.is_ascii_alphabetic()
        || (first == '.' && !rest.starts_with(|ch: char| ch.is_ascii_digit()));
    valid_start
        && rest
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || ch == '.' || ch == '_')
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every R source embedded into the binary.
    const EMBEDDED_SOURCES: &[(&str, &str)] = &[
        ("patch-pkgdepends.R", PKGDEPENDS_PATCH),
        ("revdep-prelude.R", REVDEP_PRELUDE),
        ("revdep-install.R", REVDEP_INSTALL),
        ("revdep-run.R", REVDEP_RUN),
        ("sysreqs.R", SYSREQS),
    ];

    /// Sources that are assembled behind a configuration block. These used to
    /// be Rust `format!` templates, so guard against leftover template syntax.
    /// `patch-pkgdepends.R` is excluded because it legitimately uses cli glue
    /// syntax such as `{.pkg {pkg}}`.
    const ASSEMBLED_SOURCES: &[(&str, &str)] = &[
        ("revdep-prelude.R", REVDEP_PRELUDE),
        ("revdep-install.R", REVDEP_INSTALL),
        ("revdep-run.R", REVDEP_RUN),
        ("sysreqs.R", SYSREQS),
    ];

    /// Detects `{name}` sequences left over from Rust `format!` templates.
    fn has_format_placeholder(source: &str) -> bool {
        source.split('{').skip(1).any(|tail| {
            tail.split_once('}').is_some_and(|(inner, _)| {
                !inner.is_empty() && inner.chars().all(|ch| ch.is_ascii_lowercase() || ch == '_')
            })
        })
    }

    #[test]
    fn embedded_sources_are_present() {
        for (name, source) in EMBEDDED_SOURCES {
            assert!(!source.trim().is_empty(), "{name} is empty");
            assert!(source.ends_with('\n'), "{name} must end with a newline");
            assert!(
                source.starts_with('#'),
                "{name} must open with a header comment"
            );
        }
    }

    #[test]
    fn assembled_sources_contain_no_template_syntax() {
        for (name, source) in ASSEMBLED_SOURCES {
            assert!(
                !source.contains("{{") && !source.contains("}}"),
                "{name} contains escaped braces left over from a Rust literal"
            );
            assert!(
                !has_format_placeholder(source),
                "{name} contains a Rust format placeholder"
            );
        }
    }

    #[test]
    fn config_renders_assignments_in_order_with_escaping() {
        let config = RConfig::new()
            .string("pkg_name", "O'Reilly")
            .path("repo_path", Path::new("/tmp/pkg"))
            .integer("install_workers", 8);

        assert_eq!(
            config.render(),
            "# Configuration generated by revdeprun ----\n\
             pkg_name <- 'O\\'Reilly'\n\
             repo_path <- '/tmp/pkg'\n\
             install_workers <- 8\n"
        );
    }

    #[test]
    fn empty_config_renders_header_only() {
        assert_eq!(
            RConfig::new().render(),
            "# Configuration generated by revdeprun ----\n"
        );
    }

    #[test]
    fn assemble_places_config_before_sources_in_order() {
        let config = RConfig::new().integer("n", 1);
        let script = assemble(&config, &["first <- n\n", "second <- first\n"]);

        assert_eq!(
            script,
            "# Configuration generated by revdeprun ----\n\
             n <- 1\n\
             \n\
             first <- n\n\
             \n\
             second <- first\n"
        );
    }

    #[test]
    #[should_panic(expected = "not a syntactically valid R variable name")]
    fn rejects_invalid_variable_names() {
        let _ = RConfig::new().integer("1workers", 1);
    }

    #[test]
    fn validates_r_identifiers() {
        for name in ["x", "repo_path", ".hidden", "a.b.c", "install_workers2"] {
            assert!(is_r_identifier(name), "{name} should be valid");
        }
        for name in ["", "1x", ".1x", "_x", "a-b", "a b", "a{b}", "über"] {
            assert!(!is_r_identifier(name), "{name} should be invalid");
        }
    }

    #[test]
    fn placeholder_detection_distinguishes_r_braces() {
        assert!(has_format_placeholder("install_workers <- {workers}"));
        assert!(!has_format_placeholder("f <- function(x) {\n  x\n}"));
        assert!(!has_format_placeholder("if (ok) { TRUE } else { FALSE }"));
        assert!(!has_format_placeholder("no braces"));
    }
}
